# Generated by Django 5.2.17 on 2026-09-22 09:31

import attendance.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama kantor')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_m', models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(5000)], verbose_name='Radius (meter)')),
                ('max_accuracy_m', models.PositiveIntegerField(default=75, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='Akurasi GPS maksimum')),
                ('timezone', models.CharField(default='Asia/Makassar', max_length=64)),
                ('workdays', models.JSONField(default=attendance.models.default_workdays, verbose_name='Hari kerja')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Jam masuk')),
                ('end_time', models.TimeField(default=datetime.time(17, 0), verbose_name='Jam pulang')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='Toleransi terlambat')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kantor',
                'verbose_name_plural': 'Kantor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nama lengkap')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Karyawan')], default='EMPLOYEE', max_length=16)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='attendance.office')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Belum lengkap'), ('COMPLETE', 'Selesai'), ('CORRECTED', 'Dikoreksi')], default='INCOMPLETE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='attendance.office')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'ordering': ['-work_date', 'employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jejak audit',
                'verbose_name_plural': 'Jejak audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=16)),
                ('candidate_embedding', models.BinaryField()),
                ('preview_path', models.CharField(blank=True, editable=False, max_length=255)),
                ('consent_version', models.CharField(default='2026-09', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendaftaran wajah',
                'verbose_name_plural': 'Pendaftaran wajah',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_embedding', models.BinaryField()),
                ('model_version', models.CharField(default='opencv-sface-2021dec', max_length=64)),
                ('activated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivenessChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(choices=[('CHECK_IN', 'Masuk'), ('CHECK_OUT', 'Pulang')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('ON_TIME', 'Tepat waktu'), ('LATE', 'Terlambat'), ('EARLY', 'Pulang awal'), ('COMPLETE', 'Selesai'), ('MANUAL', 'Koreksi admin')], max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('face_score', models.FloatField(blank=True, null=True)),
                ('evidence_path', models.CharField(blank=True, max_length=255)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.attendance')),
                ('challenge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.livenesschallenge')),
            ],
            options={
                'verbose_name': 'Kejadian absensi',
                'verbose_name_plural': 'Kejadian absensi',
                'ordering': ['occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('attendance', 'kind'), name='unique_attendance_event_kind')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('name', models.CharField(max_length=120, verbose_name='Keterangan')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='attendance.office')),
            ],
            options={
                'verbose_name': 'Hari libur',
                'verbose_name_plural': 'Hari libur',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('office', 'date'), name='unique_office_holiday')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_employee_workday'),
        ),
    ]
