# Generated by Django 5.2.17 on 2026-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal resign'),
        ),
    ]
