# Generated by Django 5.2.17 on 2026-09-22 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_resigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SICK', 'Sakit'), ('PERMISSION', 'Izin'), ('VACATION', 'Cuti')], default='PERMISSION', max_length=16, verbose_name='Jenis pengajuan')),
                ('start_date', models.DateField(verbose_name='Tanggal mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal selesai')),
                ('reason', models.TextField(verbose_name='Alasan / Keterangan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/%Y/%m/', verbose_name='Lampiran surat / bukti')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=16, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=300, verbose_name='Catatan peninjau')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajuan izin / cuti',
                'verbose_name_plural': 'Pengajuan izin / cuti',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
