# Generated by Django 5.2.17 on 2026-09-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def restore_approved_profiles(apps, schema_editor):
    FaceEnrollment = apps.get_model('attendance', 'FaceEnrollment')
    FaceProfile = apps.get_model('attendance', 'FaceProfile')
    employee_ids = set()
    enrollments = FaceEnrollment.objects.filter(status='APPROVED', employee__is_active=True).order_by('-submitted_at')
    for enrollment in enrollments.iterator():
        if enrollment.employee_id in employee_ids or not enrollment.candidate_embedding:
            continue
        employee_ids.add(enrollment.employee_id)
        FaceProfile.objects.get_or_create(
            employee_id=enrollment.employee_id,
            defaults={'encrypted_embedding': enrollment.candidate_embedding},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_configure_banjarmasin_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceenrollment',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Riwayat profil wajah', 'verbose_name_plural': 'Riwayat profil wajah'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.livenesschallenge'),
        ),
        migrations.RunPython(restore_approved_profiles, migrations.RunPython.noop),
    ]
